// src/components/ModulesGrid.svelte
<script lang="ts">
	import ModuleCard from './ModuleCard.svelte';
	import ModuleCardSkeleton from './ModuleCardSkeleton.svelte';
	import type { GitHubModule } from '../lib/types';

	export let modules: GitHubModule[] = [];
	export let loading = false;
	export let error: string | null = null;

	const skeletonCount = 12;
</script>

<div class="w-full">
	{#if error}
		<div class="rounded-lg border border-red-200 bg-red-50 p-6 text-center">
			<p class="mb-2 font-medium text-red-600">Failed to load modules</p>
			<p class="text-sm text-red-500">{error}</p>
		</div>
	{:else if loading}
		<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
			{#each Array(skeletonCount) as _, index (index)}
				<ModuleCardSkeleton />
			{/each}
		</div>
	{:else if modules.length === 0}
		<div class="border-sSlate-200 bg-sSlate-100 rounded-lg border p-12 text-center">
			<p class="text-sSlate-600 mb-2 font-medium">No modules found</p>
			<p class="text-sSlate-400 text-sm">Try adjusting your search or filters</p>
		</div>
	{:else}
		<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
			{#each modules as module (module.id)}
				<ModuleCard {module} />
			{/each}
		</div>
	{/if}
</div>

// src/components/ModulesGrid.tsx
import type { GitHubModule } from '../types';
import ModuleCard from './ModuleCard';
import ModuleCardSkeleton from './ModuleCardSkeleton';

interface ModulesGridProps {
  modules?: GitHubModule[];
  loading?: boolean;
  error?: string | null;
}

export default function ModulesGrid({
  modules = [],
  loading = false,
  error = null
}: ModulesGridProps) {
  const skeletonCount = 12;
  const skeletonArray = Array.from({ length: skeletonCount }, (_, index) => index);

  if (error) {
    return (
      <div className="w-full">
        <div className="rounded-lg border border-red-200 bg-red-50 p-6 text-center">
          <p className="mb-2 font-medium text-red-600">Failed to load modules</p>
          <p className="text-sm text-red-500">{error}</p>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="w-full">
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
          {skeletonArray.map((index) => (
            <ModuleCardSkeleton key={index} />
          ))}
        </div>
      </div>
    );
  }

  if (modules.length === 0) {
    return (
      <div className="w-full">
        <div className="border-sSlate-200 bg-sSlate-100 rounded-lg border p-12 text-center">
          <p className="text-sSlate-600 mb-2 font-medium">No modules found</p>
          <p className="text-sSlate-400 text-sm">Try adjusting your search or filters</p>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full">
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {modules.map((module) => (
          <ModuleCard key={module.id} module={module} />
        ))}
      </div>
    </div>
  );
}
